//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication.CRMService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cyberimpact.ca", ConfigurationName="CRMService.CRMSyncServiceSoap")]
    public interface CRMSyncServiceSoap {
        
        // CODEGEN: Generating message contract since element name customerXML from namespace http://cyberimpact.ca is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cyberimpact.ca/UpdateCustomer", ReplyAction="*")]
        ConsoleApplication.CRMService.UpdateCustomerResponse UpdateCustomer(ConsoleApplication.CRMService.UpdateCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name contactXML from namespace http://cyberimpact.ca is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cyberimpact.ca/UpdateContact", ReplyAction="*")]
        ConsoleApplication.CRMService.UpdateContactResponse UpdateContact(ConsoleApplication.CRMService.UpdateContactRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomer", Namespace="http://cyberimpact.ca", Order=0)]
        public ConsoleApplication.CRMService.UpdateCustomerRequestBody Body;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(ConsoleApplication.CRMService.UpdateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cyberimpact.ca")]
    public partial class UpdateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerXML;
        
        public UpdateCustomerRequestBody() {
        }
        
        public UpdateCustomerRequestBody(string customerXML) {
            this.customerXML = customerXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerResponse", Namespace="http://cyberimpact.ca", Order=0)]
        public ConsoleApplication.CRMService.UpdateCustomerResponseBody Body;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(ConsoleApplication.CRMService.UpdateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCustomerResponseBody {
        
        public UpdateCustomerResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContact", Namespace="http://cyberimpact.ca", Order=0)]
        public ConsoleApplication.CRMService.UpdateContactRequestBody Body;
        
        public UpdateContactRequest() {
        }
        
        public UpdateContactRequest(ConsoleApplication.CRMService.UpdateContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cyberimpact.ca")]
    public partial class UpdateContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contactXML;
        
        public UpdateContactRequestBody() {
        }
        
        public UpdateContactRequestBody(string contactXML) {
            this.contactXML = contactXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContactResponse", Namespace="http://cyberimpact.ca", Order=0)]
        public ConsoleApplication.CRMService.UpdateContactResponseBody Body;
        
        public UpdateContactResponse() {
        }
        
        public UpdateContactResponse(ConsoleApplication.CRMService.UpdateContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateContactResponseBody {
        
        public UpdateContactResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CRMSyncServiceSoapChannel : ConsoleApplication.CRMService.CRMSyncServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRMSyncServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApplication.CRMService.CRMSyncServiceSoap>, ConsoleApplication.CRMService.CRMSyncServiceSoap {
        
        public CRMSyncServiceSoapClient() {
        }
        
        public CRMSyncServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRMSyncServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMSyncServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMSyncServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication.CRMService.UpdateCustomerResponse ConsoleApplication.CRMService.CRMSyncServiceSoap.UpdateCustomer(ConsoleApplication.CRMService.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public void UpdateCustomer(string customerXML) {
            ConsoleApplication.CRMService.UpdateCustomerRequest inValue = new ConsoleApplication.CRMService.UpdateCustomerRequest();
            inValue.Body = new ConsoleApplication.CRMService.UpdateCustomerRequestBody();
            inValue.Body.customerXML = customerXML;
            ConsoleApplication.CRMService.UpdateCustomerResponse retVal = ((ConsoleApplication.CRMService.CRMSyncServiceSoap)(this)).UpdateCustomer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication.CRMService.UpdateContactResponse ConsoleApplication.CRMService.CRMSyncServiceSoap.UpdateContact(ConsoleApplication.CRMService.UpdateContactRequest request) {
            return base.Channel.UpdateContact(request);
        }
        
        public void UpdateContact(string contactXML) {
            ConsoleApplication.CRMService.UpdateContactRequest inValue = new ConsoleApplication.CRMService.UpdateContactRequest();
            inValue.Body = new ConsoleApplication.CRMService.UpdateContactRequestBody();
            inValue.Body.contactXML = contactXML;
            ConsoleApplication.CRMService.UpdateContactResponse retVal = ((ConsoleApplication.CRMService.CRMSyncServiceSoap)(this)).UpdateContact(inValue);
        }
    }
}
